/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUpgradeRouteImport } from './routes/_app/upgrade'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSeoRouteImport } from './routes/_app/seo'
import { Route as AppQualityRouteImport } from './routes/_app/quality'
import { Route as AppPerformanceRouteImport } from './routes/_app/performance'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCheckoutRouteImport } from './routes/_app/checkout'
import { Route as AppAccessibilityRouteImport } from './routes/_app/accessibility'
import { Route as AppWebsitesIndexRouteImport } from './routes/_app/websites/index'
import { Route as AppWebsitesWebsiteIdRouteImport } from './routes/_app/websites/$websiteId'
import { Route as AppIssuesIssueIdRouteImport } from './routes/_app/issues/$issueId'
import { Route as AppScansScanIdIndexRouteImport } from './routes/_app/scans/$scanId/index'
import { Route as AppScansScanIdIssuesRouteImport } from './routes/_app/scans/$scanId/issues'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoRoute = AppSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessibilityRoute = AppAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsitesIndexRoute = AppWebsitesIndexRouteImport.update({
  id: '/websites/',
  path: '/websites/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsitesWebsiteIdRoute = AppWebsitesWebsiteIdRouteImport.update({
  id: '/websites/$websiteId',
  path: '/websites/$websiteId',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesIssueIdRoute = AppIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => AppRoute,
} as any)
const AppScansScanIdIndexRoute = AppScansScanIdIndexRouteImport.update({
  id: '/scans/$scanId/',
  path: '/scans/$scanId/',
  getParentRoute: () => AppRoute,
} as any)
const AppScansScanIdIssuesRoute = AppScansScanIdIssuesRouteImport.update({
  id: '/scans/$scanId/issues',
  path: '/scans/$scanId/issues',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accessibility': typeof AppAccessibilityRoute
  '/checkout': typeof AppCheckoutRoute
  '/dashboard': typeof AppDashboardRoute
  '/performance': typeof AppPerformanceRoute
  '/quality': typeof AppQualityRoute
  '/seo': typeof AppSeoRoute
  '/settings': typeof AppSettingsRoute
  '/upgrade': typeof AppUpgradeRoute
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/websites/$websiteId': typeof AppWebsitesWebsiteIdRoute
  '/websites/': typeof AppWebsitesIndexRoute
  '/scans/$scanId/issues': typeof AppScansScanIdIssuesRoute
  '/scans/$scanId/': typeof AppScansScanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accessibility': typeof AppAccessibilityRoute
  '/checkout': typeof AppCheckoutRoute
  '/dashboard': typeof AppDashboardRoute
  '/performance': typeof AppPerformanceRoute
  '/quality': typeof AppQualityRoute
  '/seo': typeof AppSeoRoute
  '/settings': typeof AppSettingsRoute
  '/upgrade': typeof AppUpgradeRoute
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/websites/$websiteId': typeof AppWebsitesWebsiteIdRoute
  '/websites': typeof AppWebsitesIndexRoute
  '/scans/$scanId/issues': typeof AppScansScanIdIssuesRoute
  '/scans/$scanId': typeof AppScansScanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/accessibility': typeof AppAccessibilityRoute
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/seo': typeof AppSeoRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/upgrade': typeof AppUpgradeRoute
  '/_app/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/_app/websites/$websiteId': typeof AppWebsitesWebsiteIdRoute
  '/_app/websites/': typeof AppWebsitesIndexRoute
  '/_app/scans/$scanId/issues': typeof AppScansScanIdIssuesRoute
  '/_app/scans/$scanId/': typeof AppScansScanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guest'
    | '/login'
    | '/signup'
    | '/accessibility'
    | '/checkout'
    | '/dashboard'
    | '/performance'
    | '/quality'
    | '/seo'
    | '/settings'
    | '/upgrade'
    | '/issues/$issueId'
    | '/websites/$websiteId'
    | '/websites/'
    | '/scans/$scanId/issues'
    | '/scans/$scanId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guest'
    | '/login'
    | '/signup'
    | '/accessibility'
    | '/checkout'
    | '/dashboard'
    | '/performance'
    | '/quality'
    | '/seo'
    | '/settings'
    | '/upgrade'
    | '/issues/$issueId'
    | '/websites/$websiteId'
    | '/websites'
    | '/scans/$scanId/issues'
    | '/scans/$scanId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/guest'
    | '/login'
    | '/signup'
    | '/_app/accessibility'
    | '/_app/checkout'
    | '/_app/dashboard'
    | '/_app/performance'
    | '/_app/quality'
    | '/_app/seo'
    | '/_app/settings'
    | '/_app/upgrade'
    | '/_app/issues/$issueId'
    | '/_app/websites/$websiteId'
    | '/_app/websites/'
    | '/_app/scans/$scanId/issues'
    | '/_app/scans/$scanId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GuestRoute: typeof GuestRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upgrade': {
      id: '/_app/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seo': {
      id: '/_app/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AppSeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accessibility': {
      id: '/_app/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AppAccessibilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/websites/': {
      id: '/_app/websites/'
      path: '/websites'
      fullPath: '/websites/'
      preLoaderRoute: typeof AppWebsitesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/websites/$websiteId': {
      id: '/_app/websites/$websiteId'
      path: '/websites/$websiteId'
      fullPath: '/websites/$websiteId'
      preLoaderRoute: typeof AppWebsitesWebsiteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues/$issueId': {
      id: '/_app/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof AppIssuesIssueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scans/$scanId/': {
      id: '/_app/scans/$scanId/'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId/'
      preLoaderRoute: typeof AppScansScanIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scans/$scanId/issues': {
      id: '/_app/scans/$scanId/issues'
      path: '/scans/$scanId/issues'
      fullPath: '/scans/$scanId/issues'
      preLoaderRoute: typeof AppScansScanIdIssuesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccessibilityRoute: typeof AppAccessibilityRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppQualityRoute: typeof AppQualityRoute
  AppSeoRoute: typeof AppSeoRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIssuesIssueIdRoute: typeof AppIssuesIssueIdRoute
  AppWebsitesWebsiteIdRoute: typeof AppWebsitesWebsiteIdRoute
  AppWebsitesIndexRoute: typeof AppWebsitesIndexRoute
  AppScansScanIdIssuesRoute: typeof AppScansScanIdIssuesRoute
  AppScansScanIdIndexRoute: typeof AppScansScanIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessibilityRoute: AppAccessibilityRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppQualityRoute: AppQualityRoute,
  AppSeoRoute: AppSeoRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIssuesIssueIdRoute: AppIssuesIssueIdRoute,
  AppWebsitesWebsiteIdRoute: AppWebsitesWebsiteIdRoute,
  AppWebsitesIndexRoute: AppWebsitesIndexRoute,
  AppScansScanIdIssuesRoute: AppScansScanIdIssuesRoute,
  AppScansScanIdIndexRoute: AppScansScanIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GuestRoute: GuestRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
